export const LANGUAGES = [
	{
		id: "en",
		name: "English",
		flag: "https://hatscripts.github.io/circle-flags/flags/us.svg",
		api: "https://en.Eksipedia.org/w/api.php?",
		article: "https://en.Eksipedia.org/Eksi/",
	},
	{
		id: "de",
		name: "Deutsch",
		flag: "https://hatscripts.github.io/circle-flags/flags/de.svg",
		api: "https://de.Eksipedia.org/w/api.php?",
		article: "https://de.Eksipedia.org/Eksi/",
	},
	{
		id: "fr",
		name: "Français",
		flag: "https://hatscripts.github.io/circle-flags/flags/fr.svg",
		api: "https://fr.Eksipedia.org/w/api.php?",
		article: "https://fr.Eksipedia.org/Eksi/",
	},
	{
		id: "es",
		name: "Español",
		flag: "https://hatscripts.github.io/circle-flags/flags/es.svg",
		api: "https://es.Eksipedia.org/w/api.php?",
		article: "https://es.Eksipedia.org/Eksi/",
	},
	{
		id: "it",
		name: "Italiano",
		flag: "https://hatscripts.github.io/circle-flags/flags/it.svg",
		api: "https://it.Eksipedia.org/w/api.php?",
		article: "https://it.Eksipedia.org/Eksi/",
	},
	{
		id: "pt",
		name: "Português",
		flag: "https://hatscripts.github.io/circle-flags/flags/br.svg",
		api: "https://pt.Eksipedia.org/w/api.php?",
		article: "https://pt.Eksipedia.org/Eksi/",
	},
	{
		id: "ru",
		name: "Русский",
		flag: "https://hatscripts.github.io/circle-flags/flags/ru.svg",
		api: "https://ru.Eksipedia.org/w/api.php?",
		article: "https://ru.Eksipedia.org/Eksi/",
	},
	{
		id: "zh",
		name: "中文",
		flag: "https://hatscripts.github.io/circle-flags/flags/cn.svg",
		api: "https://zh.Eksipedia.org/w/api.php?",
		article: "https://zh.Eksipedia.org/Eksi/",
	},
	{
		id: "ja",
		name: "日本語",
		flag: "https://hatscripts.github.io/circle-flags/flags/jp.svg",
		api: "https://ja.Eksipedia.org/w/api.php?",
		article: "https://ja.Eksipedia.org/Eksi/",
	},
	{
		id: "ar",
		name: "العربية",
		flag: "https://hatscripts.github.io/circle-flags/flags/sa.svg",
		api: "https://ar.Eksipedia.org/w/api.php?",
		article: "https://ar.Eksipedia.org/Eksi/",
	},
	{
		id: "fa",
		name: "فارسی",
		flag: "https://hatscripts.github.io/circle-flags/flags/ir.svg",
		api: "https://fa.Eksipedia.org/w/api.php?",
		article: "https://fa.Eksipedia.org/Eksi/",
	},
	{
		id: "he",
		name: "עברית",
		flag: "https://hatscripts.github.io/circle-flags/flags/il.svg",
		api: "https://he.Eksipedia.org/w/api.php?",
		article: "https://he.Eksipedia.org/Eksi/",
	},
	{
		id: "hi",
		name: "हिन्दी",
		flag: "https://hatscripts.github.io/circle-flags/flags/in.svg",
		api: "https://hi.Eksipedia.org/w/api.php?",
		article: "https://hi.Eksipedia.org/Eksi/",
	},
	{
		id: "eu",
		name: "Euskara",
		flag: "https://hatscripts.github.io/circle-flags/flags/es-pv.svg",
		api: "https://eu.Eksipedia.org/w/api.php?",
		article: "https://eu.Eksipedia.org/Eksi/",
	},
	{
		id: "tr",
		name: "Türkçe",
		flag: "https://hatscripts.github.io/circle-flags/flags/tr.svg",
		api: "https://tr.Eksipedia.org/w/api.php?",
		article: "https://tr.Eksipedia.org/Eksi/",
	},
	{
		id: "id",
		name: "Indonesian",
		flag: "https://hatscripts.github.io/circle-flags/flags/id.svg",
		api: "https://id.Eksipedia.org/w/api.php?",
		article: "https://id.Eksipedia.org/Eksi/",
	},
	{
		id: "cs",
		name: "Čeština",
		flag: "https://hatscripts.github.io/circle-flags/flags/cz.svg",
		api: "https://cs.Eksipedia.org/w/api.php?",
		article: "https://cs.Eksipedia.org/Eksi/",
	},
	{
		id: "sk",
		name: "Slovenčina",
		flag: "https://hatscripts.github.io/circle-flags/flags/sk.svg",
		api: "https://sk.Eksipedia.org/w/api.php?",
		article: "https://sk.Eksipedia.org/Eksi/",
	},
	{
		id: "pl",
		name: "Polski",
		flag: "https://hatscripts.github.io/circle-flags/flags/pl.svg",
		api: "https://pl.Eksipedia.org/w/api.php?",
		article: "https://pl.Eksipedia.org/Eksi/",
	},
];
